// WebGPU neural upscaler: runs realesr-animevideov3-fp16 (SRVGGNetCompact,
// 18 convs) as a hand-written WGSL "mega kernel" — the whole network in one
// shader module, all weights preloaded into a single GPU buffer, all 18
// dispatches recorded into one command submit per frame.
//
// The 320x200 RGBA frame goes in via writeTexture; conv_last fuses the CRD
// DepthToSpace x4, the nearest-upsample residual add and the clamp, writing
// the 1280x800 result to a storage texture that is then blitted onto this
// upscaler's own WebGPU canvas (the game canvas already holds a WebGL2
// context, and a canvas can only have one context type).
//
// Weights come from models/realesr-animevideov3-fp16.mega.{json,bin},
// generated by tools/pack_mega_weights.py.
//
// Frames are coalesced: if one is still on the GPU when the next arrives,
// the newest frame waits and intermediate ones are dropped, so latency
// stays bounded when the engine outpaces the network (~40-50ms/frame).

"use strict";

const NN_W = 320;
const NN_H = 200;
const NN_SCALE = 4;

const NN_PRELUDE = /* wgsl */ `
enable f16;

struct Params {
  matBase : u32,
  biasBase : u32,
  slopeBase : u32,
  width : u32,
  height : u32,
};

@group(0) @binding(0) var<uniform> P : Params;
@group(0) @binding(1) var<storage, read> mats : array<mat4x4<f16>>;
@group(0) @binding(2) var<storage, read> vecs : array<vec4<f16>>;
@group(0) @binding(3) var<storage, read> src : array<vec4<f16>>;
@group(0) @binding(4) var<storage, read_write> dst : array<vec4<f16>>;
@group(0) @binding(5) var inputTex : texture_2d<f32>;
@group(0) @binding(6) var outTex : texture_storage_2d<rgba8unorm, write>;

fn prelu(a : vec4<f16>, s : vec4<f16>) -> vec4<f16> {
  return max(a, vec4<f16>()) + s * min(a, vec4<f16>());
}
`;

const NN_WGSL = NN_PRELUDE + /* wgsl */ `
const TS : u32 = 8u;               // workgroup tile is TS x TS output pixels
var<workgroup> tile1 : array<vec4<f16>, 100>;    // (TS+2)^2, first layer
var<workgroup> tile16 : array<vec4<f16>, 1600>;  // (TS+2)^2 * 16 vec4/pixel

@compute @workgroup_size(8, 8, 1)
fn conv_first(@builtin(workgroup_id) wg : vec3<u32>,
              @builtin(local_invocation_id) li : vec3<u32>,
              @builtin(local_invocation_index) lidx : u32) {
  let iw = i32(P.width); let ih = i32(P.height);
  let x0 = i32(wg.x * TS) - 1; let y0 = i32(wg.y * TS) - 1;
  for (var p = lidx; p < 100u; p += 64u) {
    let px = x0 + i32(p % 10u);
    let py = y0 + i32(p / 10u);
    var v = vec4<f16>();
    if (px >= 0 && px < iw && py >= 0 && py < ih) {
      let t = textureLoad(inputTex, vec2<i32>(px, py), 0);
      v = vec4<f16>(vec4<f32>(t.rgb, 0.0));
    }
    tile1[p] = v;
  }
  workgroupBarrier();

  var acc : array<vec4<f16>, 16>;
  for (var ov = 0u; ov < 16u; ov++) { acc[ov] = vecs[P.biasBase + ov]; }
  var m = P.matBase;
  for (var t = 0u; t < 9u; t++) {
    let v = tile1[(li.y + t / 3u) * 10u + li.x + (t % 3u)];
    for (var ov = 0u; ov < 16u; ov++) {
      acc[ov] += mats[m] * v;
      m++;
    }
  }
  let x = wg.x * TS + li.x; let y = wg.y * TS + li.y;
  if (x < P.width && y < P.height) {
    let base = (y * P.width + x) * 16u;
    for (var ov = 0u; ov < 16u; ov++) {
      dst[base + ov] = prelu(acc[ov], vecs[P.slopeBase + ov]);
    }
  }
}

fn loadTile16(wg : vec3<u32>, lidx : u32, iw : i32, ih : i32) {
  let x0 = i32(wg.x * TS) - 1; let y0 = i32(wg.y * TS) - 1;
  for (var p = lidx; p < 100u; p += 64u) {
    let px = x0 + i32(p % 10u);
    let py = y0 + i32(p / 10u);
    if (px >= 0 && px < iw && py >= 0 && py < ih) {
      let base = u32(py * iw + px) * 16u;
      for (var c = 0u; c < 16u; c++) { tile16[p * 16u + c] = src[base + c]; }
    } else {
      for (var c = 0u; c < 16u; c++) { tile16[p * 16u + c] = vec4<f16>(); }
    }
  }
  workgroupBarrier();
}

@compute @workgroup_size(8, 8, 1)
fn conv_last(@builtin(workgroup_id) wg : vec3<u32>,
             @builtin(local_invocation_id) li : vec3<u32>,
             @builtin(local_invocation_index) lidx : u32) {
  loadTile16(wg, lidx, i32(P.width), i32(P.height));

  var acc : array<vec4<f16>, 12>;
  for (var ov = 0u; ov < 12u; ov++) { acc[ov] = vecs[P.biasBase + ov]; }
  var m = P.matBase;
  for (var t = 0u; t < 9u; t++) {
    let tp = ((li.y + t / 3u) * 10u + li.x + (t % 3u)) * 16u;
    for (var iv = 0u; iv < 16u; iv++) {
      let v = tile16[tp + iv];
      for (var ov = 0u; ov < 12u; ov++) {
        acc[ov] += mats[m] * v;
        m++;
      }
    }
  }
  let x = wg.x * TS + li.x; let y = wg.y * TS + li.y;
  if (x < P.width && y < P.height) {
    // CRD DepthToSpace: HR pixel (4x+bx, 4y+by), channel c comes from
    // conv output channel c*16 + by*4 + bx = vec-group c*4+by, lane bx.
    let res = textureLoad(inputTex, vec2<i32>(i32(x), i32(y)), 0).rgb;
    for (var by = 0u; by < 4u; by++) {
      for (var bx = 0u; bx < 4u; bx++) {
        let rgb = vec3<f32>(f32(acc[by][bx]), f32(acc[4u + by][bx]),
                            f32(acc[8u + by][bx])) + res;
        textureStore(outTex, vec2<i32>(i32(x * 4u + bx), i32(y * 4u + by)),
                     vec4<f32>(clamp(rgb, vec3<f32>(0.0), vec3<f32>(1.0)), 1.0));
      }
    }
  }
}
`;

// Tuned conv_mid generator (see nn-tune.html for the measured variant sweep).
//   tw, th  threads per workgroup in x/y (workgroup covers tw*px x th pixels)
//   split   z threads per pixel, each computing 16/split output vec4s —
//           smaller accumulator arrays and more resident threads (occupancy)
//   px      output pixels per thread along x — each weight fetch feeds px FMAs
function nnMidWgsl({ tw, th, split, px }) {
  const tileW = tw * px + 2, tileH = th + 2;
  const tileN = tileW * tileH;
  const threads = tw * th * split;
  const ovn = 16 / split;
  const accs = [];
  for (let j = 0; j < px; j++) accs.push(`acc${j}`);
  return NN_PRELUDE + `
var<workgroup> tileM : array<vec4<f16>, ${tileN * 16}>;

@compute @workgroup_size(${tw}, ${th}, ${split})
fn conv_mid(@builtin(workgroup_id) wg : vec3<u32>,
            @builtin(local_invocation_id) li : vec3<u32>,
            @builtin(local_invocation_index) lidx : u32) {
  let iw = i32(P.width); let ih = i32(P.height);
  let x0 = i32(wg.x * ${tw * px}u) - 1;
  let y0 = i32(wg.y * ${th}u) - 1;
  for (var p = lidx; p < ${tileN}u; p += ${threads}u) {
    let pxx = x0 + i32(p % ${tileW}u);
    let pyy = y0 + i32(p / ${tileW}u);
    if (pxx >= 0 && pxx < iw && pyy >= 0 && pyy < ih) {
      let base = u32(pyy * iw + pxx) * 16u;
      for (var c = 0u; c < 16u; c++) { tileM[p * 16u + c] = src[base + c]; }
    } else {
      for (var c = 0u; c < 16u; c++) { tileM[p * 16u + c] = vec4<f16>(); }
    }
  }
  workgroupBarrier();

  let ovBase = li.z * ${ovn}u;
${accs.map((a) => `  var ${a} : array<vec4<f16>, ${ovn}>;`).join("\n")}
  for (var ov = 0u; ov < ${ovn}u; ov++) {
    let b = vecs[P.biasBase + ovBase + ov];
${accs.map((a) => `    ${a}[ov] = b;`).join("\n")}
  }
  for (var t = 0u; t < 9u; t++) {
    let tp = ((li.y + t / 3u) * ${tileW}u + li.x * ${px}u + (t % 3u)) * 16u;
    for (var iv = 0u; iv < 16u; iv++) {
${accs.map((a, j) => `      let v${j} = tileM[tp + ${j * 16}u + iv];`).join("\n")}
      let mb = P.matBase + (t * 16u + iv) * 16u + ovBase;
      for (var ov = 0u; ov < ${ovn}u; ov++) {
        let mat = mats[mb + ov];
${accs.map((a, j) => `        ${a}[ov] += mat * v${j};`).join("\n")}
      }
    }
  }
  let y = wg.y * ${th}u + li.y;
  if (y >= P.height) { return; }
${accs.map((a, j) => `  {
    let x = wg.x * ${tw * px}u + li.x * ${px}u + ${j}u;
    if (x < P.width) {
      let base = (y * P.width + x) * 16u;
      for (var ov = 0u; ov < ${ovn}u; ov++) {
        dst[base + ovBase + ov] = prelu(${a}[ov], vecs[P.slopeBase + ovBase + ov]);
      }
    }
  }`).join("\n")}
}
`;
}

// Fastest measured on Apple Silicon (26.5ms vs 54ms for the naive 8x8x1 mid
// kernel on an M4); needs 23040 bytes of workgroup storage. The fallback
// fits the 16KB baseline limit and still measures ~1.8x over naive.
const NN_MID_CFGS = [
  { tw: 8, th: 8, split: 4, px: 2, sharedBytes: 23040 },
  { tw: 8, th: 8, split: 2, px: 1, sharedBytes: 12800 },
];

const NN_BLIT_WGSL = /* wgsl */ `
@group(0) @binding(0) var t : texture_2d<f32>;
@vertex fn vs(@builtin(vertex_index) i : u32) -> @builtin(position) vec4<f32> {
  var p = array<vec2<f32>, 3>(vec2f(-1.0, 3.0), vec2f(-1.0, -1.0), vec2f(3.0, -1.0));
  return vec4<f32>(p[i], 0.0, 1.0);
}
@fragment fn fs(@builtin(position) pos : vec4<f32>) -> @location(0) vec4<f32> {
  return textureLoad(t, vec2<i32>(pos.xy), 0);
}
`;

class NNUpscaler {
  // Throws when WebGPU / shader-f16 / the weight files are unavailable.
  static async create(canvas) {
    if (!navigator.gpu) throw new Error("WebGPU unavailable");
    const adapter = await navigator.gpu.requestAdapter();
    if (!adapter) throw new Error("no WebGPU adapter");
    if (!adapter.features.has("shader-f16")) throw new Error("no shader-f16");
    const device = await adapter.requestDevice({
      requiredFeatures: ["shader-f16"],
      requiredLimits: { maxComputeWorkgroupStorageSize:
        Math.min(adapter.limits.maxComputeWorkgroupStorageSize, 32768) },
    });
    const [manifest, weights] = await Promise.all([
      fetch("models/realesr-animevideov3-fp16.mega.json").then((r) => {
        if (!r.ok) throw new Error(`weights manifest: HTTP ${r.status}`);
        return r.json();
      }),
      fetch("models/realesr-animevideov3-fp16.mega.bin").then((r) => {
        if (!r.ok) throw new Error(`weights: HTTP ${r.status}`);
        return r.arrayBuffer();
      }),
    ]);
    const nn = new NNUpscaler(canvas, device, manifest, weights);
    await nn.initPipelines();
    return nn;
  }

  constructor(canvas, device, manifest, weights) {
    this.canvas = canvas;
    this.device = device;
    this.dead = false;
    device.lost.then((info) => {
      this.dead = true;
      this.onDeviceLost?.(info);
    });

    canvas.width = NN_W * NN_SCALE;
    canvas.height = NN_H * NN_SCALE;
    this.ctx = canvas.getContext("webgpu");
    this.format = navigator.gpu.getPreferredCanvasFormat();
    this.ctx.configure({ device, format: this.format, alphaMode: "opaque" });

    const C = GPUShaderStage.COMPUTE;
    const uni = { buffer: { type: "uniform", hasDynamicOffset: true } };
    const ro = { buffer: { type: "read-only-storage" } };
    const rw = { buffer: { type: "storage" } };
    this.bglFirst = device.createBindGroupLayout({ entries: [
      { binding: 0, visibility: C, ...uni },
      { binding: 1, visibility: C, ...ro },
      { binding: 2, visibility: C, ...ro },
      { binding: 4, visibility: C, ...rw },
      { binding: 5, visibility: C, texture: {} },
    ]});
    this.bglMid = device.createBindGroupLayout({ entries: [
      { binding: 0, visibility: C, ...uni },
      { binding: 1, visibility: C, ...ro },
      { binding: 2, visibility: C, ...ro },
      { binding: 3, visibility: C, ...ro },
      { binding: 4, visibility: C, ...rw },
    ]});
    this.bglLast = device.createBindGroupLayout({ entries: [
      { binding: 0, visibility: C, ...uni },
      { binding: 1, visibility: C, ...ro },
      { binding: 2, visibility: C, ...ro },
      { binding: 3, visibility: C, ...ro },
      { binding: 5, visibility: C, texture: {} },
      { binding: 6, visibility: C,
        storageTexture: { access: "write-only", format: "rgba8unorm" } },
    ]});

    // Per-layer params in one uniform buffer, one 256-byte slot per layer,
    // selected with dynamic offsets.
    const nLayers = manifest.layers.length;
    this.uOffsets = manifest.layers.map((_, i) => i * 256);
    const ubuf = device.createBuffer({
      size: nLayers * 256,
      usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST });
    const udata = new Uint32Array(nLayers * 64);
    manifest.layers.forEach((l, i) => {
      udata.set([l.matBase, l.biasBase, l.slopeBase, NN_W, NN_H], i * 64);
    });
    device.queue.writeBuffer(ubuf, 0, udata);

    // The whole model in one buffer, uploaded once.
    const wbuf = device.createBuffer({
      size: weights.byteLength,
      usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST });
    device.queue.writeBuffer(wbuf, 0, weights);

    const actSize = NN_W * NN_H * 16 * 8; // 16 vec4<f16> per pixel
    this.actA = device.createBuffer({ size: actSize, usage: GPUBufferUsage.STORAGE });
    this.actB = device.createBuffer({ size: actSize, usage: GPUBufferUsage.STORAGE });

    this.inputTex = device.createTexture({
      size: [NN_W, NN_H], format: "rgba8unorm",
      usage: GPUTextureUsage.TEXTURE_BINDING | GPUTextureUsage.COPY_DST });
    this.outTex = device.createTexture({
      size: [NN_W * NN_SCALE, NN_H * NN_SCALE], format: "rgba8unorm",
      usage: GPUTextureUsage.STORAGE_BINDING | GPUTextureUsage.TEXTURE_BINDING });

    const u = { binding: 0, resource: { buffer: ubuf, size: 256 } };
    const mats = { binding: 1, resource: { buffer: wbuf } };
    const vecs = { binding: 2, resource: { buffer: wbuf } };
    const inView = this.inputTex.createView();
    this.bgFirst = device.createBindGroup({ layout: this.bglFirst, entries: [
      u, mats, vecs,
      { binding: 4, resource: { buffer: this.actA } },
      { binding: 5, resource: inView },
    ]});
    this.bgMidAB = device.createBindGroup({ layout: this.bglMid, entries: [
      u, mats, vecs,
      { binding: 3, resource: { buffer: this.actA } },
      { binding: 4, resource: { buffer: this.actB } },
    ]});
    this.bgMidBA = device.createBindGroup({ layout: this.bglMid, entries: [
      u, mats, vecs,
      { binding: 3, resource: { buffer: this.actB } },
      { binding: 4, resource: { buffer: this.actA } },
    ]});
    this.bgLast = device.createBindGroup({ layout: this.bglLast, entries: [
      u, mats, vecs,
      { binding: 3, resource: { buffer: this.actA } },
      { binding: 5, resource: inView },
      { binding: 6, resource: this.outTex.createView() },
    ]});

    this.pending = null;
    this.busy = false;
  }

  async initPipelines() {
    const device = this.device;
    this.midCfg = NN_MID_CFGS.find((c) =>
      c.sharedBytes <= device.limits.maxComputeWorkgroupStorageSize);
    const module = device.createShaderModule({ code: NN_WGSL });
    const midModule = device.createShaderModule({ code: nnMidWgsl(this.midCfg) });
    const mk = (bgl, m, entryPoint) => device.createComputePipelineAsync({
      layout: device.createPipelineLayout({ bindGroupLayouts: [bgl] }),
      compute: { module: m, entryPoint },
    });
    const blitModule = device.createShaderModule({ code: NN_BLIT_WGSL });
    [this.pFirst, this.pMid, this.pLast, this.pBlit] = await Promise.all([
      mk(this.bglFirst, module, "conv_first"),
      mk(this.bglMid, midModule, "conv_mid"),
      mk(this.bglLast, module, "conv_last"),
      device.createRenderPipelineAsync({
        layout: "auto",
        vertex: { module: blitModule, entryPoint: "vs" },
        fragment: { module: blitModule, entryPoint: "fs",
                    targets: [{ format: this.format }] },
      }),
    ]);
    this.bgBlit = device.createBindGroup({
      layout: this.pBlit.getBindGroupLayout(0),
      entries: [{ binding: 0, resource: this.outTex.createView() }],
    });
  }

  // Uint8Array, 320*200*4 RGBA. Coalesces: only the newest frame waiting.
  present(pixels) {
    this.pending = pixels;
    if (!this.busy) this.pump();
  }

  async pump() {
    this.busy = true;
    while (this.pending && !this.dead) {
      const pixels = this.pending;
      this.pending = null;
      const device = this.device;
      device.queue.writeTexture({ texture: this.inputTex }, pixels,
        { bytesPerRow: NN_W * 4 }, [NN_W, NN_H]);

      const gx = Math.ceil(NN_W / 8), gy = Math.ceil(NN_H / 8);
      const mgx = Math.ceil(NN_W / (this.midCfg.tw * this.midCfg.px));
      const mgy = Math.ceil(NN_H / this.midCfg.th);
      const encoder = device.createCommandEncoder();
      const pass = encoder.beginComputePass();
      pass.setPipeline(this.pFirst);
      pass.setBindGroup(0, this.bgFirst, [this.uOffsets[0]]);
      pass.dispatchWorkgroups(gx, gy);
      pass.setPipeline(this.pMid);
      for (let i = 0; i < 16; i++) {
        pass.setBindGroup(0, i % 2 === 0 ? this.bgMidAB : this.bgMidBA,
          [this.uOffsets[1 + i]]);
        pass.dispatchWorkgroups(mgx, mgy);
      }
      pass.setPipeline(this.pLast);
      pass.setBindGroup(0, this.bgLast, [this.uOffsets[17]]);
      pass.dispatchWorkgroups(gx, gy);
      pass.end();

      const rp = encoder.beginRenderPass({ colorAttachments: [{
        view: this.ctx.getCurrentTexture().createView(),
        loadOp: "clear", clearValue: [0, 0, 0, 1], storeOp: "store" }] });
      rp.setPipeline(this.pBlit);
      rp.setBindGroup(0, this.bgBlit);
      rp.draw(3);
      rp.end();
      device.queue.submit([encoder.finish()]);
      await device.queue.onSubmittedWorkDone();
    }
    this.busy = false;
  }
}
